# Generated by Django 5.0.4 on 2024-05-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dish_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик блюд'),
        ),
    ]
