# Generated by Django 4.2.7 on 2023-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0002_alter_dishes_options_dishes_cat_id_dishes_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
