# Generated by Django 4.2.7 on 2023-11-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0003_alter_dishes_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото блюда'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%d', verbose_name='Видео приготовления'),
        ),
    ]
