# Generated by Django 4.2.7 on 2023-11-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0004_dishes_photo_dishes_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
