# Generated by Django 4.2.7 on 2023-11-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0008_remove_dishes_dislike_remove_dishes_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='like',
        ),
        migrations.AddField(
            model_name='dishes',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
