# Generated by Django 4.2.7 on 2023-11-16 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_recipes', '0009_remove_dishes_dislike_remove_dishes_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='like',
        ),
        migrations.AddField(
            model_name='dishes',
            name='like',
            field=models.ManyToManyField(related_name='liked_dishes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
