# Generated by Django 4.2.7 on 2024-04-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0010_remove_dishes_dislike_remove_dishes_like_dishes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='bgc/%Y/%m/%d/', verbose_name='Картинка категории'),
        ),
    ]
