# Generated by Django 4.2.7 on 2024-04-22 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_recipes', '0011_category_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_dishes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
