# Generated by Django 4.2.7 on 2024-04-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0012_alter_dishes_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание шага')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app_recipes.dishes', verbose_name='Блюдо')),
            ],
        ),
    ]
