# Generated by Django 4.2.7 on 2024-04-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0013_stepdishes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepdishes',
            options={'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.AddField(
            model_name='stepdishes',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='steps/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
