# Generated by Django 4.2.7 on 2024-04-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0015_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='dish_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='app_recipes.dishes', verbose_name='Блюдо'),
        ),
    ]
