# Generated by Django 4.2.7 on 2024-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0016_comments_dish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='count_comments',
            field=models.IntegerField(default=0, verbose_name='Счетчик комментариев'),
        ),
    ]
