# Generated by Django 4.2.7 on 2024-04-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0017_comments_count_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='count_comments',
        ),
    ]
