# Generated by Django 5.0.4 on 2024-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0018_remove_comments_count_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Приготовление'),
        ),
    ]
